name: Exosphere Mongo service
description: Generic MongoDB storage service

setup: npm install
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port


messages:
  receives:
    - mongo.create
    - mongo.list
    - mongo.get-details
    - mongo.update
    - mongo.delete
  sends:
    - mongo.created
    - mongo.listed
    - mongo.details
    - mongo.not-found
    - mongo.updated
    - mongo.deleted
