name: Exosphere Mongo service
description: Generic MongoDB storage service

setup: npm install
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port


messages:
  receives:
    - tweets.create
    - tweets.list
    - tweets.get-details
    - tweets.update
    - tweets.delete
  sends:
    - tweets.created
    - tweets.listed
    - tweets.details
    - tweets.not-found
    - tweets.updated
    - tweets.deleted
